// This file is automatically generated. Do not edit it directly.
import env from "@/env";
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

export type UserProfile = {
  id: string;
  email: string;
  full_name: string;
  age: number | null;
  height: number | null;
  weight: number;
  created_at: string;
};

export const supabase = createClient<Database>(
  env.VITE_SUPABASE_URL,
  env.VITE_SUPABASE_ANON_KEY
);
